#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DavesGamesMVC.LinqToSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dwk-multiple-projects")]
	public partial class ChainLetterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ChainLetterDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dwk_multiple_projectsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChainLetterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChainLetterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChainLetterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChainLetterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserModel> UserModels
		{
			get
			{
				return this.GetTable<UserModel>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="mlm.AddUser")]
		public int AddUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UplineName", DbType="NVarChar(50)")] string uplineName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uplineName, userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="mlm.GetUser")]
		public ISingleResult<UserModel> GetUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((ISingleResult<UserModel>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="mlm.UserModel")]
	public partial class UserModel
	{
		
		private string _UserName;
		
		private string _u1Name;
		
		private string _u2Name;
		
		private string _u3Name;
		
		private string _u4Name;
		
		private string _u5Name;
		
		public UserModel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u1Name", DbType="NVarChar(50)")]
		public string u1Name
		{
			get
			{
				return this._u1Name;
			}
			set
			{
				if ((this._u1Name != value))
				{
					this._u1Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u2Name", DbType="NVarChar(50)")]
		public string u2Name
		{
			get
			{
				return this._u2Name;
			}
			set
			{
				if ((this._u2Name != value))
				{
					this._u2Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u3Name", DbType="NVarChar(50)")]
		public string u3Name
		{
			get
			{
				return this._u3Name;
			}
			set
			{
				if ((this._u3Name != value))
				{
					this._u3Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u4Name", DbType="NVarChar(50)")]
		public string u4Name
		{
			get
			{
				return this._u4Name;
			}
			set
			{
				if ((this._u4Name != value))
				{
					this._u4Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u5Name", DbType="NVarChar(50)")]
		public string u5Name
		{
			get
			{
				return this._u5Name;
			}
			set
			{
				if ((this._u5Name != value))
				{
					this._u5Name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
