#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DavesGamesMVC.DatabaseAccess.TimerToys
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dwk-multiple-projects")]
	public partial class TimerToysDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TimerToysDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dwk_multiple_projectsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.AdjustTimer")]
		public int AdjustTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Char(36)")] string timerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Offset", DbType="Int")] System.Nullable<int> offset)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey, offset);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.DeleteTimer")]
		public int DeleteTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Char(36)")] string timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.SelectAllByPage")]
		public ISingleResult<SelectAllByPageResult> SelectAllByPage([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey);
			return ((ISingleResult<SelectAllByPageResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.UpdatePageName")]
		public int UpdatePageName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageName", DbType="NVarChar(150)")] string pageName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, pageName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.UpdateTimerName")]
		public int UpdateTimerName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Char(36)")] string timerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerName", DbType="NVarChar(150)")] string timerName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey, timerName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.InsertNewTimer")]
		public int InsertNewTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.InsertNewPage")]
		public ISingleResult<InsertNewPageResult> InsertNewPage()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<InsertNewPageResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.ToggleTimer")]
		public int ToggleTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Char(36)")] string timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.ResetTimer")]
		public int ResetTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Char(36)")] string timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SelectAllByPageResult
	{
		
		private string _TimerKey;
		
		private string _TimerName;
		
		private System.Nullable<int> _SortIndex;
		
		private System.Nullable<bool> _IsReadOnly;
		
		private System.Nullable<bool> _IsRunning;
		
		private System.Nullable<int> _ElapsedTime;
		
		public SelectAllByPageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimerKey", DbType="Char(36)")]
		public string TimerKey
		{
			get
			{
				return this._TimerKey;
			}
			set
			{
				if ((this._TimerKey != value))
				{
					this._TimerKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimerName", DbType="NVarChar(150)")]
		public string TimerName
		{
			get
			{
				return this._TimerName;
			}
			set
			{
				if ((this._TimerName != value))
				{
					this._TimerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortIndex", DbType="Int")]
		public System.Nullable<int> SortIndex
		{
			get
			{
				return this._SortIndex;
			}
			set
			{
				if ((this._SortIndex != value))
				{
					this._SortIndex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReadOnly", DbType="Bit")]
		public System.Nullable<bool> IsReadOnly
		{
			get
			{
				return this._IsReadOnly;
			}
			set
			{
				if ((this._IsReadOnly != value))
				{
					this._IsReadOnly = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRunning", DbType="Bit")]
		public System.Nullable<bool> IsRunning
		{
			get
			{
				return this._IsRunning;
			}
			set
			{
				if ((this._IsRunning != value))
				{
					this._IsRunning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTime", DbType="Int")]
		public System.Nullable<int> ElapsedTime
		{
			get
			{
				return this._ElapsedTime;
			}
			set
			{
				if ((this._ElapsedTime != value))
				{
					this._ElapsedTime = value;
				}
			}
		}
	}
	
	public partial class InsertNewPageResult
	{
		
		private string _PageKey;
		
		public InsertNewPageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageKey", DbType="Char(36)")]
		public string PageKey
		{
			get
			{
				return this._PageKey;
			}
			set
			{
				if ((this._PageKey != value))
				{
					this._PageKey = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
