#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DavesGamesMVC.DatabaseAccess.TimerToys
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dwk-multiple-projects")]
	public partial class TimerToysDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TimerToysDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dwk_multiple_projectsConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TimerToysDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LinkModel> LinkModels
		{
			get
			{
				return this.GetTable<LinkModel>();
			}
		}
		
		public System.Data.Linq.Table<PageModel> PageModels
		{
			get
			{
				return this.GetTable<PageModel>();
			}
		}
		
		public System.Data.Linq.Table<TimerModel> TimerModels
		{
			get
			{
				return this.GetTable<TimerModel>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.InsertLink")]
		public int InsertLink([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.InsertPage")]
		public ISingleResult<InsertPageResult> InsertPage()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<InsertPageResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.InsertTimer")]
		public int InsertTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.SelectLinks")]
		public ISingleResult<LinkModel> SelectLinks([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey);
			return ((ISingleResult<LinkModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.SelectPage")]
		public ISingleResult<PageModel> SelectPage([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey);
			return ((ISingleResult<PageModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.SelectTimers")]
		public ISingleResult<TimerModel> SelectTimers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey);
			return ((ISingleResult<TimerModel>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.UpdatePageName")]
		public int UpdatePageName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageName", DbType="NVarChar(150)")] string pageName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, pageName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.AdjustTimer")]
		public int AdjustTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Int")] System.Nullable<int> timerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Offset", DbType="Int")] System.Nullable<int> offset)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey, offset);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.ResetTimer")]
		public int ResetTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Int")] System.Nullable<int> timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.ToggleTimer")]
		public int ToggleTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Int")] System.Nullable<int> timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.UpdateLinkName")]
		public int UpdateLinkName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinkKey", DbType="Int")] System.Nullable<int> linkKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinkName", DbType="NVarChar(150)")] string linkName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, linkKey, linkName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.UpdateLinkUrl")]
		public int UpdateLinkUrl([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinkKey", DbType="Int")] System.Nullable<int> linkKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinkUrl", DbType="NVarChar(MAX)")] string linkUrl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, linkKey, linkUrl);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.UpdateTimerName")]
		public int UpdateTimerName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Int")] System.Nullable<int> timerKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerName", DbType="NVarChar(150)")] string timerName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey, timerName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.DeleteTimer")]
		public int DeleteTimer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimerKey", DbType="Int")] System.Nullable<int> timerKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, timerKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="tt.DeleteLink")]
		public int DeleteLink([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PageKey", DbType="Char(36)")] string pageKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LinkKey", DbType="Int")] System.Nullable<int> linkKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pageKey, linkKey);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tt.LinkModel")]
	public partial class LinkModel
	{
		
		private int _LinkKey;
		
		private string _LinkName;
		
		private string _LinkUrl;
		
		public LinkModel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkKey", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int LinkKey
		{
			get
			{
				return this._LinkKey;
			}
			set
			{
				if ((this._LinkKey != value))
				{
					this._LinkKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string LinkName
		{
			get
			{
				return this._LinkName;
			}
			set
			{
				if ((this._LinkName != value))
				{
					this._LinkName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkUrl", DbType="NVarChar(MAX)")]
		public string LinkUrl
		{
			get
			{
				return this._LinkUrl;
			}
			set
			{
				if ((this._LinkUrl != value))
				{
					this._LinkUrl = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tt.PageModel")]
	public partial class PageModel
	{
		
		private string _PageKey;
		
		private string _ReadOnlyKey;
		
		private string _PageName;
		
		private System.Nullable<bool> _IsReadOnly;
		
		public PageModel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageKey", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string PageKey
		{
			get
			{
				return this._PageKey;
			}
			set
			{
				if ((this._PageKey != value))
				{
					this._PageKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadOnlyKey", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string ReadOnlyKey
		{
			get
			{
				return this._ReadOnlyKey;
			}
			set
			{
				if ((this._ReadOnlyKey != value))
				{
					this._ReadOnlyKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string PageName
		{
			get
			{
				return this._PageName;
			}
			set
			{
				if ((this._PageName != value))
				{
					this._PageName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReadOnly", DbType="Bit")]
		public System.Nullable<bool> IsReadOnly
		{
			get
			{
				return this._IsReadOnly;
			}
			set
			{
				if ((this._IsReadOnly != value))
				{
					this._IsReadOnly = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="tt.TimerModel")]
	public partial class TimerModel
	{
		
		private int _TimerKey;
		
		private string _TimerName;
		
		private int _IsRunning;
		
		private System.Nullable<int> _ElapsedTime;
		
		public TimerModel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimerKey", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int TimerKey
		{
			get
			{
				return this._TimerKey;
			}
			set
			{
				if ((this._TimerKey != value))
				{
					this._TimerKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimerName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string TimerName
		{
			get
			{
				return this._TimerName;
			}
			set
			{
				if ((this._TimerName != value))
				{
					this._TimerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRunning", DbType="Int NOT NULL")]
		public int IsRunning
		{
			get
			{
				return this._IsRunning;
			}
			set
			{
				if ((this._IsRunning != value))
				{
					this._IsRunning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElapsedTime", DbType="Int")]
		public System.Nullable<int> ElapsedTime
		{
			get
			{
				return this._ElapsedTime;
			}
			set
			{
				if ((this._ElapsedTime != value))
				{
					this._ElapsedTime = value;
				}
			}
		}
	}
	
	public partial class InsertPageResult
	{
		
		private string _PageKey;
		
		public InsertPageResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageKey", DbType="Char(36)")]
		public string PageKey
		{
			get
			{
				return this._PageKey;
			}
			set
			{
				if ((this._PageKey != value))
				{
					this._PageKey = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
